name: Deploy to S3

# master 브랜치에 push가 발생했을 때만 실행
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. 의존성 설치
      - name: Install Dependencies
        run: npm ci

      # 4. 프로젝트 빌드
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      # 5. AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 6. S3에 빌드 파일 업로드
      - name: Upload to S3
        run: |
          echo "Syncing build files to S3..."
          aws s3 sync dist/ s3://kuad-archive/2025/ \
            --delete \
            --cache-control "max-age=31536000"

      # 7. CloudFront 캐시 무효화
      - name: Invalidate CloudFront
        run: |
          echo "Creating CloudFront invalidation..."
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/2025/*"

      # 8. 배포 완료 알림
      - name: Deployment Status
        run: |
          echo "Deployment completed successfully!"
